#datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
#mybatis
mybatis:
  type-aliases-package: com.dj.springboot.pojo
  mapper-locations: classpath:mapper/*.xml